import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../services/locale_provider.dart';

class AppStrings {
  AppStrings._();

  static const Map<String, Map<String, String>> _values = {
    'ar': {
      'app_name': 'مـرورك',
      'app_tagline': 'خدمات المرور بين يديك',
      'home': 'الرئيسية',
      'my_vehicles': 'مركباتي',
      'violations': 'المخالفات',
      'my_license': 'رخصتي',
      'profile': 'حسابي',
      'welcome': 'مرحباً بك،',
      'citizen': 'المواطن',
      'emergency_777': 'طوارئ 777',
      'total_fines': 'المخالفات المستحقة',
      'unpaid_violations': 'مخالفات غير مدفوعة',
      'all_clear': 'سجلك نظيف! لا توجد مخالفات مسجلة',
      'quick_pay': 'سداد فوري',
      'pay_all': 'سداد الكل',
      'view_all': 'عرض الكل',
      'quick_services': 'الخدمات السريعة',
      'vehicle_status': 'حالة المركبات',
      'registered_vehicles': 'مركباتي المسجلة',
      'no_vehicles': 'لا توجد مركبات مسجلة باسمك حالياً',
      'add_vehicle_btn': 'إضافة مركبة جديدة',
      'emergency_report': 'بلاغ طوارئ',
      'active': 'سارية',
      'expired': 'منتهية',
      'digital_license': 'رخصتي الرقمية',
      'digital_license_full': 'بطاقة رخصة القيادة الرقمية',
      'traffic_announcements': 'التعاميم والتنبيهات المرورية',
      'recent_violations': 'أحدث المخالفات',
      'no_violations': 'لا توجد مخالفات مسجلة',
      'pay_now': 'سداد الآن',
      'dispute': 'اعتراض',
      'paid': 'مسددة',
      'unpaid': 'غير مسددة',
      'all': 'الكل',
      'verified': 'موثقة',
      'under_review': 'قيد المراجعة',
      'fine_amount': 'قيمة الغرامة',
      'details_and_qr': 'التفاصيل والـ QR',
      'violations_record': 'سجل المخالفات والغرامات',
      'search_violations_hint': 'ابحث برقم اللوحة، الموقع، أو نوع المخالفة...',
      'total_unpaid': 'المجموع غير المسدد:',
      'no_violations_category': 'لا توجد مخالفات في هذه الفئة',
      'clean_record_msg': 'سجل القيادة نظيف والالتزام بالقوانين مستمر',
      'vehicles_management': 'إدارة المركبات والتراخيص',
      'search_vehicles_hint': 'ابحث برقم اللوحة، الماركة، أو الموديل...',
      'personal_info_section': 'البيانات والمعلومات الشخصية',
      'app_settings_section': 'إعدادات النظام والمظهر',
      'privacy_support_section': 'الخصوصية، المعايير والمساعدة',
      'app_language': 'لغة التطبيق (Language)',
      'arabic_lang': 'العربية (السودان)',
      'english_lang': 'English (United States)',
      'dark_mode_title': 'الوضع المظلم (Dark Mode)',
      'dark_mode_active': 'مفعل (الملكي الداكن)',
      'dark_mode_inactive': 'الوضع النهاري الفاتح',
      'notifications_title': 'إشعارات المخالفات والرسائل',
      'notifications_subtitle': 'تنبيه فوري عند تسجيل أي مخالفة',
      'radar_alerts_title': 'تنبيهات السرعة والرادار',
      'radar_alerts_subtitle': 'تنبيه السائق بنقاط التهدئة المرورية',
      'privacy_policy_title': 'سياسة الاستخدام والخصوصية',
      'privacy_policy_subtitle': 'معايير حماية البيانات وأمان أندرويد',
      'emergency_center_title': 'طوارئ وغرفة عمليات المرور (777)',
      'about_app_title': 'حول التطبيق ومعايير النظام',
      'signout_btn': 'تسجيل الخروج من الحساب',
      'confirm_signout': 'تأكيد تسجيل الخروج',
      'confirm_signout_msg': 'هل أنت متأكد من رغبتك في تسجيل الخروج من التطبيق؟',
      'national_id_label': 'الرقم الوطني:',
      'officer_badge_label': 'رقم الشارة:',
      'phone_label': 'رقم الهاتف',
      'city_label': 'المدينة / المنطقة',
      'address_label': 'العنوان السكني',
      'license_number_label': 'رقم الرخصة:',
      'state_label': 'الولاية:',
      'name_label': 'الاسم:',
      'sudan_republic': 'جمهورية السودان',
      'national_driver_license': 'رخصة قيادة وطنية',
      'tap_to_flip': 'اضغط على البطاقة للوجه الآخر',
      'license_status_valid': 'حالة الرخصة: سارية وموثقة',
      'license_expiry_date': 'تاريخ الانتهاء: 2028/11/15',
      'license_rules_title': 'تعليمات:',
      'license_rule_1': '1. يجب حمل هذه الرخصة أثناء القيادة.',
      'license_rule_2': '2. يعاقب القانون على تزوير أو إساءة استخدامها.',
      'officer_account_tag': 'حساب ضابط مرور معتمد',
      'citizen_account_tag': 'حساب مواطن موثق',
      'vehicles_stat': 'المركبات',
      'violations_stat': 'المخالفات',
      'amounts_stat': 'المبالغ',
      'currency_sdg': 'ج.س',
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب جديد',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'forgot_password': 'نسيت كلمة المرور؟',
      'logout': 'تسجيل الخروج',
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'arabic': 'العربية',
      'english': 'English',
      'dark_mode': 'الوضع الداكن',
      'notifications': 'الإشعارات',
      'enable_notifications': 'تفعيل الإشعارات والتنبيهات',
      'terms_privacy': 'الشروط وسياسة الخصوصية',
      'app_version': 'إصدار التطبيق',
      'check_updates': 'فحص التحديثات',
      'help_support': 'المساعدة والدعم الفني',
      'edit_profile': 'تعديل البيانات الشخصية',
      'change_password': 'تغيير كلمة المرور',
      'save_changes': 'حفظ التغييرات',
      'cancel': 'إلغاء',
      'confirm': 'تأكيد',
      'loading': 'جاري التحميل...',
      'success': 'تمت العملية بنجاح',
      'error': 'حدث خطأ، يرجى المحاولة لاحقاً',
      'payment_gateway': 'بوابة السداد الإلكتروني',
      'select_payment_method': 'اختر طريقة الدفع',
      'bankak_direct': 'تطبيق بنكك (سداد مباشر)',
      'fawry': 'تطبيق فوري (بنك فيصل)',
      'card_ebs': 'بطاقة صراف آلي (EBS)',
      'account_number': 'رقم الحساب البنكي',
      'enter_pin': 'أدخل رمز الـ PIN السري',
      'confirm_and_pay': 'تأكيد وخصم المبلغ',
      'receipt': 'إيصال السداد الإلكتروني',
      'transaction_id': 'رقم المعاملة',
      'amount_paid': 'المبلغ المسدد',
      'date': 'التاريخ',
      'status': 'الحالة',
      'download_receipt': 'تحميل الإيصال',
      'new_violation_alert': '⚠️ تم قيد مخالفة مرورية جديدة',
      'new_violation_body': 'تم رصد وقيد مخالفة جديدة على مركبتك. اضغط للتفاصيل والسداد.',
      'sovereign_title': 'جمهورية السودان - وزارة الداخلية',
      'sovereign_subtitle': 'منظومة مـرورك - خدمات المرور بين يديك',
      'search_vehicles': 'البحث في المركبات...',
      'add_vehicle': 'إضافة مركبة',
      'plate_number': 'رقم اللوحة',
      'owner_name': 'اسم المالك',
      'chassis_number': 'رقم الشاسيه',
      'model_year': 'سنة الصنع',
      'color': 'اللون',
    },
    'en': {
      'app_name': 'Mororak',
      'app_tagline': 'Traffic services in your hands',
      'home': 'Home',
      'my_vehicles': 'Vehicles',
      'violations': 'Violations',
      'my_license': 'License',
      'profile': 'Profile',
      'welcome': 'Welcome,',
      'citizen': 'Citizen',
      'emergency_777': 'Emergency 777',
      'total_fines': 'Outstanding Fines',
      'unpaid_violations': 'unpaid violations',
      'all_clear': 'All clear! No violations recorded',
      'quick_pay': 'Quick Pay',
      'pay_all': 'Pay All',
      'view_all': 'View All',
      'quick_services': 'Quick Services',
      'vehicle_status': 'Vehicle Status',
      'registered_vehicles': 'My Registered Vehicles',
      'no_vehicles': 'No vehicles registered under your name',
      'add_vehicle_btn': 'Add New Vehicle',
      'emergency_report': 'Emergency Call',
      'active': 'Active',
      'expired': 'Expired',
      'digital_license': 'Digital License',
      'digital_license_full': 'Digital Driver License Card',
      'traffic_announcements': 'Traffic Announcements',
      'recent_violations': 'Recent Violations',
      'no_violations': 'No violations recorded',
      'pay_now': 'Pay Now',
      'dispute': 'Dispute',
      'paid': 'Paid',
      'unpaid': 'Unpaid',
      'all': 'All',
      'verified': 'Verified',
      'under_review': 'Under Review',
      'fine_amount': 'Fine Amount',
      'details_and_qr': 'Details & QR',
      'violations_record': 'Violations & Fines Record',
      'search_violations_hint': 'Search plate, location, or violation type...',
      'total_unpaid': 'Total Unpaid:',
      'no_violations_category': 'No violations in this category',
      'clean_record_msg': 'Clean driving record and full traffic compliance',
      'vehicles_management': 'Vehicles & License Management',
      'search_vehicles_hint': 'Search plate, make, or model...',
      'personal_info_section': 'Personal Information',
      'app_settings_section': 'System & Appearance Settings',
      'privacy_support_section': 'Privacy, Standards & Support',
      'app_language': 'App Language',
      'arabic_lang': 'العربية (السودان)',
      'english_lang': 'English (United States)',
      'dark_mode_title': 'Dark Mode',
      'dark_mode_active': 'Enabled (Royal Dark)',
      'dark_mode_inactive': 'Light Mode',
      'notifications_title': 'Violations & Messages Alerts',
      'notifications_subtitle': 'Instant alerts upon new violations',
      'radar_alerts_title': 'Speed & Radar Alerts',
      'radar_alerts_subtitle': 'Alert driver at speed zones',
      'privacy_policy_title': 'Privacy Policy & Terms',
      'privacy_policy_subtitle': 'Data protection and Android security',
      'emergency_center_title': 'Emergency Operations Center (777)',
      'about_app_title': 'About App & System Standards',
      'signout_btn': 'Sign Out',
      'confirm_signout': 'Confirm Sign Out',
      'confirm_signout_msg': 'Are you sure you want to sign out?',
      'national_id_label': 'National ID:',
      'officer_badge_label': 'Badge Number:',
      'phone_label': 'Phone Number',
      'city_label': 'City / Area',
      'address_label': 'Residential Address',
      'license_number_label': 'License No:',
      'state_label': 'State:',
      'name_label': 'Name:',
      'sudan_republic': 'Republic of Sudan',
      'national_driver_license': 'National Driver License',
      'tap_to_flip': 'Tap the card to flip',
      'license_status_valid': 'License Status: Valid & Verified',
      'license_expiry_date': 'Expiry Date: 2028/11/15',
      'license_rules_title': 'Instructions:',
      'license_rule_1': '1. This license must be carried while driving.',
      'license_rule_2': '2. Forgery or misuse is strictly punishable by law.',
      'officer_account_tag': 'Authorized Police Officer',
      'citizen_account_tag': 'Verified Citizen Account',
      'vehicles_stat': 'Vehicles',
      'violations_stat': 'Violations',
      'amounts_stat': 'Fines',
      'currency_sdg': 'SDG',
      'login': 'Sign In',
      'register': 'Create Account',
      'email': 'Email Address',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'logout': 'Sign Out',
      'settings': 'Settings',
      'language': 'Language',
      'arabic': 'العربية',
      'english': 'English',
      'dark_mode': 'Dark Mode',
      'notifications': 'Notifications',
      'enable_notifications': 'Enable Notifications & Alerts',
      'terms_privacy': 'Terms & Privacy Policy',
      'app_version': 'App Version',
      'check_updates': 'Check for Updates',
      'help_support': 'Help & Support',
      'edit_profile': 'Edit Profile',
      'change_password': 'Change Password',
      'save_changes': 'Save Changes',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'loading': 'Loading...',
      'success': 'Success',
      'error': 'An error occurred, please try again',
      'payment_gateway': 'Payment Gateway',
      'select_payment_method': 'Select Payment Method',
      'bankak_direct': 'Bankak App (Direct Pay)',
      'fawry': 'Fawry App (Faisal Bank)',
      'card_ebs': 'ATM Card (EBS Network)',
      'account_number': 'Bank Account Number',
      'enter_pin': 'Enter Secret PIN',
      'confirm_and_pay': 'Confirm & Pay',
      'receipt': 'Payment Receipt',
      'transaction_id': 'Transaction ID',
      'amount_paid': 'Amount Paid',
      'date': 'Date',
      'status': 'Status',
      'download_receipt': 'Download Receipt',
      'new_violation_alert': '⚠️ New Traffic Violation Recorded',
      'new_violation_body': 'A new violation has been recorded on your vehicle. Tap to review and pay.',
      'sovereign_title': 'Republic of Sudan - Ministry of Interior',
      'sovereign_subtitle': 'Mororak System - Traffic Services in Your Hands',
      'search_vehicles': 'Search vehicles...',
      'add_vehicle': 'Add Vehicle',
      'plate_number': 'Plate Number',
      'owner_name': 'Owner Name',
      'chassis_number': 'Chassis Number',
      'model_year': 'Model Year',
      'color': 'Color',
    },
  };

  static String tr(String key, [String langCode = 'ar']) {
    return _values[langCode]?[key] ?? _values['ar']?[key] ?? key;
  }
}

extension AppLocalizationContext on BuildContext {
  String tr(String key) {
    try {
      final provider = watch<LocaleProvider>();
      return AppStrings.tr(key, provider.languageCode);
    } catch (_) {
      return AppStrings.tr(key, 'ar');
    }
  }

  bool get isArabic {
    try {
      return watch<LocaleProvider>().isArabic;
    } catch (_) {
      return true;
    }
  }
}
